### ISSUE TITLE
spike: non-Chapel reproducer for mprotect(2) hang on ARM

### ISSUE THREAD

**Issue by gbtitus** [chapel-lang/chapel#10840]
We think we're seeing programs running on ARM compute nodes hang in `mprotect(2)` if they do a lot of calls to that.  This happens with tasks=qthreads with guard pages enabled when a program creates lots of tasks, because Qthreads uses `mprotect()` to create guard pages on each task's stack.  The job for this spike is to write a non-Chapel reproducer for this behavior, which we can hand off to OS folks to study.

**Comment by gbtitus** [comment]
I can reproduce a hang, but interestingly it's not a hang in `mprotect()`.  It's a hang in pthread condition variable processing, which is also implicated in the Chapel hangs because although there we typically see 2 threads in `mprotect()` the rest are in pthread condition variable processing.  Here is the final version of what I was working with: [many-mprotect-3.zip](https://github.com/chapel-lang/chapel/files/2349922/many-mprotect-3.zip).  I ran it within a job started like this:

```
qsub -I -l place=scatter,walltime=0:05:00,select=1:nodetype=mom-aarch64+1:nodetype=TX264 -V
```

I ran it 100 times, like this:

```
for i in $(seq 100) ; do echo ============ ; echo $i ; aprun -cc none -d64 -n1 -N1 -j0 ./many-mprotect-3 -t64 -n1000 -w500000 -p ; done
```

On the 11th run it hung and I used `pcmd kill -ABRT ...` to kill the process and get a core file:

```
============
11
64 threads, 1000 cycles, 500000 usecs condWait per cycle.
starting cycle 0
starting cycle 100
starting cycle 200
[... several minutes pass with no output ...]
Application 13638960 exit signals: Aborted
Application 13638960 resources: utime ~848s, stime ~14729s, Rss ~5788, inblocks ~0, outblocks ~0
```

I got tracebacks from `gdb` for all the threads and processed those to make all the data argument addresses the same so I could compare them.  1 thread was here:

```
[gbt@kay-aarch:tmp] more thr-1.txtp
(gdb) #0  0x0000000020011c58 in __pthread_mutex_lock (mutex=<ADDR>)
    at pthread_mutex_lock.c:81
#1  0x0000000020001d88 in main ()
(gdb)
```

1 thread was here:

```
[gbt@kay-aarch:tmp] more thr-9.txtp
(gdb) #0  0x00000000200125ac in __pthread_mutex_unlock_usercnt (
    mutex=mutex@entry=<ADDR>, decr=decr@entry=0)
    at pthread_mutex_unlock.c:66
#1  0x0000000020012774 in __pthread_cond_timedwait (cond=<ADDR>,
    mutex=<ADDR>, abstime=<ADDR>)
    at pthread_cond_timedwait.c:75
#2  0x000000002000223c in thrNextCycle ()
#3  0x0000000020002060 in thrFn ()
#4  0x00000000200109a0 in start_thread (arg=<ADDR>)
    at pthread_create.c:336
#5  0x000000002003f1c0 in thread_start ()
(gdb)
```

1 thread was here:

```
[gbt@kay-aarch:tmp] more thr-27.txtp
(gdb) #0  0x000000002001334c in __lll_lock_wait (futex=futex@entry=<ADDR>,
    private=0) at lowlevellock.c:43
#1  0x00000000200144f0 in __pthread_mutex_cond_lock (mutex=<ADDR>)
    at ../nptl/pthread_mutex_lock.c:81
#2  0x0000000020012a28 in __pthread_cond_timedwait (cond=<ADDR>,
    mutex=<ADDR>, abstime=<ADDR>)
    at pthread_cond_timedwait.c:262
#3  0x000000002000223c in thrNextCycle ()
#4  0x0000000020002060 in thrFn ()
#5  0x00000000200109a0 in start_thread (arg=<ADDR>)
    at pthread_create.c:336
#6  0x000000002003f1c0 in thread_start ()
(gdb)
```

And finally, 62 threads were here:

```
[gbt@kay-aarch:tmp] more thr-2.txtp
(gdb) #0  0x0000000020012878 in __pthread_cond_timedwait (cond=<ADDR>,
    mutex=<ADDR>, abstime=<ADDR>)
    at pthread_cond_timedwait.c:198
#1  0x000000002000223c in thrNextCycle ()
#2  0x0000000020002060 in thrFn ()
#3  0x00000000200109a0 in start_thread (arg=<ADDR>)
    at pthread_create.c:336
#4  0x000000002003f1c0 in thread_start ()
(gdb)
```

**Comment by gbtitus** [comment]
I'm going to close this spike now; it's timed out and we have to decide on our next step(s).
