### ISSUE TITLE
param/nonparam differences in virtual dispatch with default values

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#14167]
One aspect of #13962 seems problematic to me, whatever decision is
reached in that issue -- the behavior depends on whether the
default values are params.

```chapel
proc f() {
  return 0;
}

proc g() {
  return 1;
}

class Parent {
  proc method(arg:int = f()) {
    writeln("in Parent.method arg=", arg);
  }
}

class Child : Parent {
  override proc method(arg:int = g()) {
    writeln("in Child.method arg=", arg);
  }
}

proc main() {
  var x:Parent = new Child();
  x.method();
  // should the above call:
  //   1. be in error (or maybe the error is elsewhere in the program)
  //   2. run child's default (virtually dispatched) `g()` and so print out `in Child.method arg=1`
  //   3. run parent's default `f()` and so print out `in Child.method arg=0`
}
```

edit: Move discussion of options 1 and 2 to #13962.

But either way, I think letting the behavior depend on whether the
default values are params is bad, and that's what happens today.

Reiterating [my comment in that issue](https://github.com/chapel-lang/chapel/issues/13962#issuecomment-529743194)

```chapel
proc f() { return 0; }
proc g() { return 1; }
```

as written above results in

```chapel
  var x:Parent = new Child();
  x.method();
```

reporting `In Child.method arg=1`.

But

```chapel
proc f() param { return 0; }
proc g() param { return 1; }
```

results in `In Child.method arg=0`.

And as a bonus,

```chapel
proc f()       { return 0; }
proc g() param { return 1; }
```

results in

```
internal error: seg fault [util/misc.cpp:672]

(gdb) i s
#0  0x00000000011dd1c0 in ?? ()
#1  0x00000000004dbb10 in Symbol::isRef (this=0x9139a00) at symbol.cpp:216
#2  0x000000000044f4ef in pruneVisit (sym=0x9139a00, fns=..., types=...) at astutil.cpp:803
#3  0x000000000044fbd7 in visitVisibleFunctions (fns=..., types=...) at astutil.cpp:869
#4  0x0000000000450484 in prune () at astutil.cpp:1028
#5  0x000000000059127c in runPass (tracker=..., passIndex=22, isChpldoc=false) at runpasses.cpp:207
#6  0x0000000000591160 in runPasses (tracker=..., isChpldoc=false) at runpasses.cpp:169
#7  0x000000000058d014 in main (argc=2, argv=0x7fffffffde88) at driver.cpp:1535
```
edit: under interpretation 2, I believe this is a valid program.

**Associated Future Test(s):**

None yet

### Configuration Information

```
chpl version 1.21.0 pre-release (b18ef88)
Copyright (c) 2004-2019, Cray Inc.  (See LICENSE file for more details)

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
```

**Comment by cassella** [comment]
These cases all work now, at least as of #17653, which added some of  these cases as tests.  I opened #21302 to add tests of the mixed param/non-param cases, which also works now.

**Comment by cassella** [comment]
With the tests added in #21302, closing this issue.

**Comment by cassella** [comment]
Good grief, I got myself all confused.  #21302 hasn't been merged yet.
