### ISSUE TITLE
compiler-generated initializer for a record containing a sync variable leads to invalid read, segfault

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#15951]
### Summary of Problem

**Source Code:**

```chapel
record R {var f$: sync int;}
var five$: sync int = 5;
var r = new R(five$);
```

**Execution command:**

```
fortytwo@magrathea:~/src/chapel (master)$ ./foo-none 
Segmentation fault (core dumped)
```

```
==7535== Thread 2:
==7535== Invalid read of size 8
==7535==    at 0x1B9DF8: chpl_je_arena_mapbitsp_read (arena.h:802)
==7535==    by 0x1B9DF8: chpl_je_arena_mapbits_get (arena.h:809)
==7535==    by 0x1B9DF8: chpl_je_arena_mapbits_binind_get (arena.h:866)
==7535==    by 0x1B9DF8: chpl_je_arena_salloc (arena.h:1387)
==7535==    by 0x1B9DF8: chpl_je_isalloc (jemalloc_internal.h:1054)
==7535==    by 0x1B9DF8: chpl_je_p2rz (jemalloc_internal.h:1152)
==7535==  Address 0x10 is not stack'd, malloc'd or (recently) free'd
==7535== 
```

```
(gdb) r
Starting program: /home/fortytwo/src/chapel/foo-none 
...

Thread 2 "foo-none" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff69ff700 (LWP 7306)]
chpl_je_arena_mapbits_get (pageind=0, chunk=0x0)
    at /home/fortytwo/src/chapel/third-party/jemalloc/jemalloc-src/include/jemalloc/internal/arena.h:809
809             return (arena_mapbitsp_read(arena_mapbitsp_get_const(chunk, pageind)));
(gdb) i s
#0  chpl_je_arena_mapbits_get (pageind=0, chunk=0x0)
    at /home/fortytwo/src/chapel/third-party/jemalloc/jemalloc-src/include/jemalloc/internal/arena.h:809
#1  chpl_je_arena_dalloc (slow_path=false, tcache=<optimized out>, ptr=0x5, tsdn=<optimized out>)
    at /home/fortytwo/src/chapel/third-party/jemalloc/jemalloc-src/include/jemalloc/internal/arena.h:1434
#2  chpl_je_idalloctm (slow_path=false, is_metadata=false, tcache=<optimized out>, ptr=0x5, tsdn=<optimized out>)
    at include/jemalloc/internal/jemalloc_internal.h:1170
#3  chpl_je_iqalloc (slow_path=false, tcache=<optimized out>, ptr=0x5, tsd=<optimized out>) at include/jemalloc/internal/jemalloc_internal.h:1187
#4  ifree (tsd=<optimized out>, slow_path=false, tcache=<optimized out>, ptr=0x5)
    at /home/fortytwo/src/chapel/third-party/jemalloc/jemalloc-src/src/jemalloc.c:1896
#5  chpl_je_free (ptr=0x5) at /home/fortytwo/src/chapel/third-party/jemalloc/jemalloc-src/src/jemalloc.c:2016
#6  0x0000555555562618 in chpl_free ()
#7  0x000055555556288e in chpl_mem_free ()
#8  0x00005555555ad3ac in chpl_here_free ()
#9  0x000055555557ddb4 in deinit_chpl21 ()
#10 0x00005555555b62dd in chpl.deinit_foo ()
#11 0x000055555559cf32 in chpl_deinitModules ()
#12 0x00005555555b6289 in chpl_gen_main ()
#13 0x00005555555d5d5e in chpl_executable_init ()
#14 0x00005555555d999d in chapel_wrapper ()
#15 0x00005555556487aa in qthread_wrapper (ptr=0x7ffff6a25000) at /home/fortytwo/src/chapel/third-party/qthread/qthread-src/src/qthread.c:2175
#16 0x0000000000000000 in ?? ()
```

I expect it's the same problem, but this program exhibits the error
differently.  And though the test case is a little more complex, the
failure seems more direct, rather than buried in jemalloc during
module deinit:

```chapel
import Set;

record R {var f$: sync int;}
var five$: sync int = 5;
var r = new R(five$);

var s = new Set.set(R);
s.add(r);
```

```
==8236== Invalid read of size 8
==8236==    at 0x1FC7ED: qthread_readFE (feb.c:1469)
==8236==  Address 0xd is not stack'd, malloc'd or (recently) free'd
```

```
Thread 2 "foo-none" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff69ff700 (LWP 8346)]
0x00005555556487ed in qthread_readFE (dest=0x7fffee7fdd10, src=0xd) at /home/fortytwo/src/chapel/third-party/qthread/qthread-src/src/feb.c:1469
1469                *(aligned_t *)dest = *(aligned_t *)src;
(gdb) i s
#0  0x00005555556487ed in qthread_readFE (dest=0x7fffee7fdd10, src=0xd) at /home/fortytwo/src/chapel/third-party/qthread/qthread-src/src/feb.c:1469
#1  0x000055555557e291 in readFE_chpl2 ()
#2  0x000055555557dfcc in readFE_chpl ()
#3  0x000055555557deab in init_ASSIGN__chpl3 ()
#4  0x00005555555b9887 in init_ASSIGN__chpl8 ()
#5  0x00005555555b95fe in chpl.init_foo ()
#6  0x00005555555b96db in chpl_gen_main ()
#7  0x00005555555d975e in chpl_executable_init ()
```

It seems to be due to the compiler-generated initializer.  This is
clean in valgrind:

```chapel
record R {var f$: sync int; proc init(v: int) { f$ = v;} }
var five$: sync int = 5;
var r = new R(five$.readFE());
```

**Associated Future Test(s):**

None yet

### Configuration Information

```
chpl version 1.23.0 pre-release (0dca038669)

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none

gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
```

**Comment by cassella** [comment]
The first case now is clean (but for a deprecation warning) compiled normally, but trips an internal error with `--verify`:

```
fortytwo@enodia:~/src/chapel (main)$ chpl --verify foo.chpl
foo.chpl:1: In module 'foo':
foo.chpl:3: warning: Initializing a type-inferred variable from a 'sync' is deprecated; apply a '.read??()' method to the right-hand side
foo.chpl:3: internal error: actual formal type mismatch for init: int(64) != _syncvar(int(64)) [main//home/fortytwo/src/chapel/compiler/main/checks.cpp:896]
```

The second case now fails with

```
foo.chpl:1: In module 'foo':
foo.chpl:5: warning: Initializing a type-inferred variable from a 'sync' is deprecated; apply a '.read??()' method to the right-hand side
foo.chpl:3: warning: implicitly reading from a sync is deprecated; apply a 'read??()' method to the actual
foo.chpl:3: warning: implicitly reading from a sync is deprecated; apply a 'read??()' method to the actual
foo.chpl:3: warning: implicitly reading from a sync is deprecated; apply a 'read??()' method to the actual
$CHPL_HOME/modules/internal/ChapelBase.chpl:2530: In function 'chpl_field_neq':
$CHPL_HOME/modules/internal/ChapelBase.chpl:2531: warning: implicitly reading from a sync is deprecated; apply a 'read??()' method to the actual
$CHPL_HOME/modules/internal/ChapelBase.chpl:2531: warning: implicitly reading from a sync is deprecated; apply a 'read??()' method to the actual
  foo.chpl:3: called as chpl_field_neq(a: _syncvar(int(64)), b: _syncvar(int(64)))
note: generic instantiations are underlined in the above callstack
foo.chpl:3: error: const actual is passed to 'ref' formal 'a' of chpl_field_neq()
$CHPL_HOME/modules/internal/ChapelSyncvar.chpl:138: note: to formal of type _syncvar(int(64))
$CHPL_HOME/modules/internal/ChapelSyncvar.chpl:138: note: id 1391772
$CHPL_HOME/modules/internal/ChapelBase.chpl:2530: note: to ref formal here
$CHPL_HOME/modules/internal/ChapelBase.chpl:2530: note: id 1416825
foo.chpl:3: error: const actual is passed to 'ref' formal 'b' of chpl_field_neq()
$CHPL_HOME/modules/internal/ChapelSyncvar.chpl:138: note: to formal of type _syncvar(int(64))
$CHPL_HOME/modules/internal/ChapelSyncvar.chpl:138: note: id 1391772
$CHPL_HOME/modules/internal/ChapelBase.chpl:2530: note: to ref formal here
$CHPL_HOME/modules/internal/ChapelBase.chpl:2530: note: id 1416827
```

I imagine once support for that deprecated initialization is removed entirely, that internal error and those weird const `chpl_field_neg()` things won't be reachable.  I'll just let this lie in the meantime.

**Comment by bradcray** [comment]
I think the situation here is much better now thanks to work by @jabraham17 this year.  Specifically, we decided that we weren't comfortable (for now at least) with having the compiler generate default initializers for fields of sync or atomic tyoe, so the compiler currently is generating the error:

```chapel
testit.chpl:1: warning: compiler generated default initializers for records with 'sync' fields are deprecated, please supply an 'init' method
```

(where I predict that, ultimately, it seems likely that we'll have a `sync t` field support a compiler-generated initializer that takes an argument of type `t` to initialize it rather than `sync t`.  And ditto for `atomic t`.  But one step at a time).

We also currently generate this error:

```chapel
testit.chpl:3: warning: Initializing a type-inferred variable from a 'sync' is deprecated; apply a '.read??()' method to the right-hand side
```

which I'm not quite making sense of at the moment in this context.  Unless it's stemming from the `this.f = five;` that the compiler is essentially generating until the deprecation is removed (which I think we're about due for?).  At that point, the first error will probably turn into a warning and the second will go away as we remove the implicit reads/writes...?
