### ISSUE TITLE
compiler segfault with method lifetime constraint e > this

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#16012]
### Summary of Problem

**Source Code:**

```chapel
record foo {
  type eltType = int;
  var element: eltType;
  proc _getRef(ref e: eltType) ref: eltType lifetime e > this{
    return e;
  }
  proc set(x: eltType) {
    _getRef(element) = x;
  }    
}

var x = new foo();
x.set(3);
writeln(x.element);
```

**Compile command:**

```
fortytwo@magrathea:~/src/chapel (master)$ chpl foo.chpl
internal error: seg fault [util/misc.cpp:691]

fortytwo@magrathea:~/src/chapel (master)$ chpl --no-devel foo.chpl
internal error: UTI-MIS-0691 chpl version 1.23.0 pre-release (45d6becc88)
```

**Associated Future Test(s):**

None yet

### Configuration Information

```
chpl version 1.23.0 pre-release (45d6becc88)

CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: none
CHPL_AUX_FILESYS: none

gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
```

**Comment by cassella** [comment]
gdb says

```
Program received signal SIGSEGV, Segmentation fault.
0x00005555558a372d in (anonymous namespace)::LifetimeState::inferredLifetimeForCall (this=0x7fffffffdb00, call=0x55555ebe94d0) at lifetime.cpp:1259
1259        if (sym->defPoint->getFunction() != calledFn)

(gdb) i s
#0  0x00005555558a372d in (anonymous namespace)::LifetimeState::inferredLifetimeForCall (this=0x7fffffffdb00, call=0x55555ebe94d0) at lifetime.cpp:1259
#1  0x00005555558a4583 in (anonymous namespace)::LifetimeState::inferredLifetimeForExpr (this=0x7fffffffdb00, rhsExpr=0x55555ebe94d0, usedAsRef=true, 
    usedAsBorrow=false) at lifetime.cpp:1400
#2  0x00005555558a77c6 in (anonymous namespace)::InferLifetimesVisitor::enterCallExpr (this=0x7fffffffda70, call=0x55555ebe9200) at lifetime.cpp:2249
#3  0x0000555555609f48 in CallExpr::accept (this=0x55555ebe9200, visitor=0x7fffffffda70) at CallExpr.cpp:670
#4  0x000055555565b52b in BlockStmt::accept (this=0x55555ebe6eb0, visitor=0x7fffffffda70) at stmt.cpp:749
#5  0x000055555562b4dc in FnSymbol::accept (this=0x55555ebe6390, visitor=0x7fffffffda70) at FnSymbol.cpp:820
#6  0x00005555558a09bf in checkLifetimesInFunction (fn=0x55555ebe6390) at lifetime.cpp:472
#7  0x00005555558a0328 in checkFunction (fn=0x55555ebe6390) at lifetime.cpp:420
#8  0x00005555558a0210 in checkLifetimesAndNilDereferences () at lifetime.cpp:404
#9  0x0000555555837bd8 in callDestructors () at callDestructors.cpp:1804
#10 0x000055555571be36 in runPass (tracker=..., passIndex=19, isChpldoc=false) at runpasses.cpp:208
#11 0x000055555571bcfc in runPasses (tracker=..., isChpldoc=false) at runpasses.cpp:170
#12 0x0000555555717c9f in main (argc=2, argv=0x7fffffffdec8) at driver.cpp:1579
```
