### ISSUE TITLE
Recursive iterator produces internal error while printing it, or using break in for loop in its iteration.

### ISSUE THREAD

**Issue by rchinmay** [chapel-lang/chapel#17085]
### Summary of Problem

Printing a recursive iterator's yielded values using ``writeln()`` produces internal error on compilation. But, if it were expanded with a for loop on its elements and then print its elements, it does not produce any error, and also executes as expected. But in such a loop, if we use a break condition inside the for loop, then it produces internal error. In the source code given below, if the ``for b in a(n-1) do {`` is replaced by ``for b in 1..(n-1) by -1 do {``, then it works as expected. So, I assumed this problem was arising because of the recursive part in iterator. I don't know any reasons for which such statements should not compile. I was expecting it to produce similar output as using ``1..(n-1) by -1`` in the place of ``a(n-1)``.

### Steps to Reproduce

**Source Code:**

```chapel
iter a(n):int {
  yield n;
  if n!=1 then {
    for b in a(n-1) do {    //replacing with for b in 1..(n-1) by -1 works
      yield b;
    }
  }
}

writeln(a(10));      //Cauing internal error

for  p in a(10) do {
  write(p, ' ');
  if p<5 then break;  //Causing internal error
}
writeln();
```

**Compile command:**

``chpl Chapel_Program.chpl``

**Output on compilation:**
```
internal error: UTI-MIS-0788 chpl version 1.23.0

Internal errors indicate a bug in the Chapel compiler ("It's us, not you"),
and we're sorry for the hassle.  We would appreciate your reporting this bug -- 
please see https://chapel-lang.org/bugs.html for instructions.  In the meantime,
the filename + line number above may be useful in working around the issue.
```

**Execution command:**

If the ``writeln(a(10));`` and ``if p<5 then break;`` are commented or ``for b in a(n-1) do {`` is replaced by ``for b in 1..(n-1) by -1 do {``, then using ``./Chapel_Program`` for execution works well.

### Configuration Information

- Output of `chpl --version`: 
```
chpl version 1.23.0
Copyright 2020 Hewlett Packard Enterprise Development LP
Copyright 2004-2019 Cray Inc.
(See LICENSE file for more details)
```
- Output of `$CHPL_HOME/util/printchplenv --anonymize`:
```
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none *
CHPL_TASKS: fifo *
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: cstdlib *
CHPL_ATOMICS: cstdlib
CHPL_GMP: none *
CHPL_HWLOC: none
CHPL_REGEXP: none *
CHPL_LLVM: none *
CHPL_AUX_FILESYS: none
```
- Back-end compiler and version, e.g. `gcc --version` or `clang --version`:
```
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by Yash1256** [comment]
> Printing a recursive iterator's yielded values using writeln() produces internal error on compilation.

@rchinmay The following code is not causing any Internal error, It is giving output without any errors
### Code 
```chapel
iter a(n):int {
  yield n;
  if n!=1 then {
    for b in a(n-1) do {    //replacing with for b in 1..(n-1) by -1 works
      yield b;
    }
  }
}

writeln(a(10));      //Cauing internal error
``` 

### Output 
```
10 9 8 7 6 5 4 3 2 1
```
![Output](https://user-images.githubusercontent.com/56587507/106916313-07fad380-672d-11eb-9e19-1a6e1ea382d7.png)

```chapel
for  p in a(10) do {
  write(p, ' ');
  if p<5 then break;  //Causing internal error
}
writeln();
```
When adding this to code makes compilation error in the code because of the if statement line otherwise it's working fine.

**Comment by bradcray** [comment]
@Yash1256: Note that TIO is now several versions behind the official Chapel release, so isn't a good way of determining what does or doesn't work currently.

@rchinmay: Thanks for reporting this.  Recursive iterators are a known challenge in the Chapel implementation.  Would you let me know whether this is blocking your progress, or whether you're just reporting it having encountered it?

**Comment by rchinmay** [comment]
@Yash1256 I had only tried on my local desktop before creating this issue. However, using TIO (online compiler) did not solve this problem either. ``writeln(a(10))`` part works well. But if the break line included, then it produces weird results. I have attached screenshots for the same. In TIO, code with the break statement, and without writeln statement produces compilation error that the break label is used but not mentioned, but I feel the break usage should work since it is inside the for loop and I don't feel anything wrong with its usage here.
But using both these lines, i.e., the exact source code which I have used in issue, produces internal error. I feel this ambiguity is because TIO uses chapel version 1.20, but I have tried it on 1.23 version in my local desktop. Also, replacing ``a(n-1)`` with ``1..(n-1) by -1`` works well even with the break statement. So, I feel the break or the if statement is not wrong in usage here.

- Commenting writeln(a(10)) gives ambigious error, telling that break statement is used but not labelled or defined.

![Screenshot from 2021-02-04 23-17-53](https://user-images.githubusercontent.com/53946759/106933796-5add8680-673f-11eb-8c18-1164d3c885ed.png)

- Using explicit label also gives similar error.

![Screenshot from 2021-02-04 23-17-20](https://user-images.githubusercontent.com/53946759/106933806-5e710d80-673f-11eb-9f52-6787324225e5.png)

- Replacing a(n-1) with 1..(n-1) by -1 works well as expected

![Screenshot from 2021-02-04 23-16-23](https://user-images.githubusercontent.com/53946759/106933813-60d36780-673f-11eb-8ddc-fe84ed0bccc4.png)

- Produces Internal error on uncommenting ``writeln(a(10))``

![Screenshot from 2021-02-04 23-15-41](https://user-images.githubusercontent.com/53946759/106933818-62049480-673f-11eb-8e43-7d738f4705d3.png)

**Comment by rchinmay** [comment]
@bradcray Thanks for clarifying. I was trying to reproduce the Seive of Erosthenes part from [here](https://github.com/greensoftwarelab/RosettaExamples/blob/master/Sieve-of-Eratosthenes/Chapel/sieve-of-eratosthenes-2.chapel). But it was producing internal errors on my local computer. Trying out various variants, I found that it was because of recursive iterators. Hence used a simple program to verify it and opened this issue.

**Comment by bradcray** [comment]
Got it, thanks for the context.  Recursive iterators are powerful, which is why we've tried to continue maintaining them, but also reasonably difficult for the compiler to analyze well and implement efficiently, which is why they tend to be a fragile feature.  In our implementation, they are also fairly heavyweight by nature, so generally any code designed for high performance will avoid them (and maybe this is why that version was so expensive).  The paper was written using Chapel 1.15 I believe, and it would not surprise me if support for recursive iterators with conditional breaks (or other cases) had degraded since that time.  We do have some libraries and tests that exercise recursive iterators, but beyond the few patterns we test, I don't believe we have very deep coverage of them.  Since you're already well-versed in Chapel PRs, if you're willing / interested, it could be useful to file a [.future test](https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/bestPractices/TestSystem.rst#a-test-that-tracks-a-failure) logging this behavior and linking it to this issue.

**Comment by bradcray** [comment]
@rchinmay: Now that #17143 is merged, would you consider editing the OP here to include pointers to the futures?  If you look at the template for new issues in our GitHub, you'll see a section like this:

```
**Associated Future Test(s):**
<!-- Are there any tests in Chapel's test system that demonstrate this issue?
     e.g. [`test/path/to/foo.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/path/to/foo.chpl
          ) #1234 -->
```

where if you edit the comments out, update the two paths to point to your test, and update the PR number, you should get a nice hyperlink to the file and PR that introduced it.  Then make a second copy with different paths for the second future.

**Comment by cassella** [comment]
For reference, with today's compiler (f7ea19ea58) I get these stack traces from the two futures:

`break-iterating-recursive-iterator.chpl`:

```
[Detaching after vfork from child process 386305]
pure virtual method called
terminate called without an active exception

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) i s
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff7a5f864 in __GI_abort () at abort.c:79
#2  0x00007ffff7e2fa31 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7e3b4fc in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7e3b567 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7e3c2e5 in __cxa_pure_virtual () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x0000555555699bfc in Symbol::isRef (this=0x5555582960a0) at symbol.cpp:235
#7  0x000055555563c214 in Expr::isRef (this=0x5555638258f0) at expr.cpp:116
#8  0x00005555557705f5 in propagateCopies (symExprs=std::vector of length 1, capacity 1 = {...}, available=std::map with 0 elements)
    at copyPropagation.cpp:433
#9  0x0000555555770e34 in localCopyPropagationCore (bb=0x555556083ce0, available=std::map with 0 elements, 
    ravailable=std::map with 0 elements, liveRefs=std::set with 0 elements) at copyPropagation.cpp:625
#10 0x0000555555770fd7 in localCopyPropagation (fn=0x555558c143e0) at copyPropagation.cpp:648
#11 0x000055555577212e in copyPropagation () at copyPropagation.cpp:938
#12 0x0000555555768a1d in runPass (tracker=..., passIndex=28, isChpldoc=false) at runpasses.cpp:208
#13 0x00005555557688d8 in runPasses (tracker=..., isChpldoc=false) at runpasses.cpp:170
#14 0x000055555576460e in main (argc=2, argv=0x7fffffffdd48) at driver.cpp:1719
```

and for `write-recursive-iter.chpl`:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000555555702991 in SymExpr::codegen (this=0x5555594dbb50) at cg-expr.cpp:174
174         ret = var->codegen();
(gdb) i s
#0  0x0000555555702991 in SymExpr::codegen (this=0x5555594dbb50) at cg-expr.cpp:174
#1  0x000055555573f319 in GotoStmt::codegen (this=0x555562ce9ff0) at cg-stmt.cpp:325
#2  0x000055555572ddcb in AList::codegen (this=0x555556013380, separator=0x555555bd9dc2 "") at cg-alist.cpp:36
#3  0x000055555573ec7b in BlockStmt::codegen (this=0x555556013320) at cg-stmt.cpp:146
#4  0x000055555573f0bc in CondStmt::codegen (this=0x55555c621d10) at cg-stmt.cpp:229
#5  0x000055555572ddcb in AList::codegen (this=0x555563302540, separator=0x555555bd9dc2 "") at cg-alist.cpp:36
#6  0x000055555573ec7b in BlockStmt::codegen (this=0x5555633024e0) at cg-stmt.cpp:146
#7  0x000055555573f0bc in CondStmt::codegen (this=0x55555603c0d0) at cg-stmt.cpp:229
#8  0x000055555572ddcb in AList::codegen (this=0x55555786c270, separator=0x555555bd9dc2 "") at cg-alist.cpp:36
#9  0x000055555573ec7b in BlockStmt::codegen (this=0x55555786c210) at cg-stmt.cpp:146
#10 0x0000555555746735 in FnSymbol::codegenDef (this=0x555558f223f0) at cg-symbol.cpp:2660
#11 0x0000555555748ceb in ModuleSymbol::codegenDef (this=0x5555568da010) at cg-symbol.cpp:3159
#12 0x00005555556f1ddc in codegenPartTwo () at codegen.cpp:2582
#13 0x00005555556f2137 in codegen () at codegen.cpp:2644
#14 0x0000555555768a1d in runPass (tracker=..., passIndex=40, isChpldoc=false) at runpasses.cpp:208
#15 0x00005555557688d8 in runPasses (tracker=..., isChpldoc=false) at runpasses.cpp:170
#16 0x000055555576460e in main (argc=2, argv=0x7fffffffdd58) at driver.cpp:1719
```

**Comment by bradcray** [comment]
The future added for this in https://github.com/chapel-lang/chapel/pull/17143 has started passing nondeterministically, and increasingly frequently (e.g., on a 100 trial run, I saw 69 passes and 31 failures), which makes it hard to keep testing nightly.  In https://github.com/chapel-lang/chapel/pull/24272, I've added a .notest to the test for the time being, where we should only consider closing this issue if we get it to pass 100% of the time.

I continue to be surprised and puzzled about the nondeterministic behavior, since I thought we'd removed most sources of nondeterminism from the compiler by now....

Tagging @DanilaFe on this since he's been looking at recursion recently.  But Daniel, note that I consider this low priority given how complex recursive iterators are and how rarely they're used, at least until it's preventing a user from progressing.  And I think it's also unrelated w.r.t. where you've been looking at recursion, so this is more a thematic ping than anything (at first, I was hoping maybe your changes were why things had started passing :) ).
