### ISSUE TITLE
printchplenv crashes when CHPL_TARGET_COMPILER=llvm and CHPL_LLVM=none

### ISSUE THREAD

**Issue by jhh67** [chapel-lang/chapel#18770]
`printchplenv` crashes when `CHPL_TARGET_COMPILER=llvm` and `CHPL_LLVM=none`. It works if `CHPL_TARGET_COMPILER` is not set to `llvm`, or if `CHPL_LLVM` is set to either `bundled` or `system`.

```
C02<chapel-lang/main main 4796> printenv | grep -i llvm                                                                                                     main
CHPL_TARGET_COMPILER=llvm
CHPL_LLVM=none

C02<chapel-lang/main main 4797> printchplenv                                                                                                                main
Traceback (most recent call last):
  File "/Users/jhh/git/chapel-lang/main/util/chplenv/printchplenv.py", line 494, in <module>
    main()
  File "/Users/jhh/git/chapel-lang/main/util/chplenv/printchplenv.py", line 483, in main
    compute_all_values()
  File "/Users/jhh/git/chapel-lang/main/util/chplenv/printchplenv.py", line 208, in compute_all_values
    chpl_compiler.validate_compiler_settings()
  File "/Users/jhh/git/chapel-lang/main/util/chplenv/utils.py", line 33, in memoize_wrapper
    cache[args] = func(*args)
  File "/Users/jhh/git/chapel-lang/main/util/chplenv/chpl_compiler.py", line 384, in validate_compiler_settings
    validate_inference_matches('target', 'c')
  File "/Users/jhh/git/chapel-lang/main/util/chplenv/chpl_compiler.py", line 365, in validate_inference_matches
    inferred = get_compiler_from_command(cmd)
  File "/Users/jhh/git/chapel-lang/main/util/chplenv/chpl_compiler.py", line 241, in get_compiler_from_command
    first = command.split()[0]
IndexError: list index out of range

```

**Comment by bradcray** [comment]
@jhh67 : Thanks for capturing this.  I've tried to put together a quick fix in #18837.
