### ISSUE TITLE
Weird "index out of range" error in chpl_compiler.py

### ISSUE THREAD

**Issue by bradcray** [chapel-lang/chapel#18977]
While building a secondary configuration to the one mentioned in#18973, I:
* set `CHPL_LLVM=bundled`
* re-built Chapel

Without changing my chplconfig file (s.t. it still said `CHPL_LLVM=none`), I tried compiling with:

```bash
$ chpl test/release/examples/primers/locales.chpl -O --target-compiler=llvm
```

thinking "this will be a way to override `chplconfig` and use the LLVM back-end."  Instead, I got:

```
Traceback (most recent call last):
  File "/lustre/software/chapel/apollo/chapel-1.25.1/util/chplenv/printchplenv.py", line 496, in <module>
    main()
  File "/lustre/software/chapel/apollo/chapel-1.25.1/util/chplenv/printchplenv.py", line 485, in main
    compute_all_values()
  File "/lustre/software/chapel/apollo/chapel-1.25.1/util/chplenv/printchplenv.py", line 210, in compute_all_values
    chpl_compiler.validate_compiler_settings()
  File "/lustre/software/chapel/apollo/chapel-1.25.1/util/chplenv/utils.py", line 33, in memoize_wrapper
    cache[args] = func(*args)
  File "/lustre/software/chapel/apollo/chapel-1.25.1/util/chplenv/chpl_compiler.py", line 386, in validate_compiler_settings
    validate_inference_matches('target', 'c')
  File "/lustre/software/chapel/apollo/chapel-1.25.1/util/chplenv/chpl_compiler.py", line 367, in validate_inference_matches
    inferred = get_compiler_from_command(cmd[0])
  File "/lustre/software/chapel/apollo/chapel-1.25.1/util/chplenv/chpl_compiler.py", line 241, in get_compiler_from_command
    first = command.split()[0]
IndexError: list index out of range
error: 'CHPL_HOME=/lustre/software/chapel/apollo/chapel-1.25.1 CHPL_RUNTIME_INCL=/lustre/software/chapel/apollo/chapel-1.25.1/runtime/include CHPL_RUNTIME_LIB=/lustre/software/chapel/apollo/chapel-1.25.1/lib CHPL_TARGET_COMPILER=llvm CHPL_THIRD_PARTY=/lustre/software/chapel/apollo/chapel-1.25.1/third-party CHPLENV_SUPPRESS_WARNINGS=true /lustre/software/chapel/apollo/chapel-1.25.1/util/printchplenv --all --internal --no-tidy --simple' did not run successfully
```

When I removed the `CHPL_LLVM=none` line from my `chplconfig` file, I was able to compile without problems.

**Comment by mppf** [comment]
This could be the same issue as #18973. E.g. `"".split()[0]` fails in a similar way.
