### ISSUE TITLE
internal error for class with param field whose default value is another, non-param, field.

### ISSUE THREAD

**Issue by cassella** [chapel-lang/chapel#8443]
### Summary of Problem

This is a variation of #8423: a different non-param source of the param field's default value leads to different incorrect behavior.

### Steps to Reproduce

**Source Code:**

```chapel
class C {
  var notaparam = 42;
  param p = notaparam;
  proc init() { }
}

var c = new C();
writeln(c);
delete c;
```

I expected ``default value for param is not a param``.  Instead,

```
$ chpl param-field-default-value-non-param-field.chpl 
internal error: seg fault [misc.cpp:564]
```

As in the other issue, it compiles without the writeln().

**Associated Future Test(s):**
[`test/classes/initializers/generics/param-field-default-value-non-param-field.chpl`](
           https://github.com/chapel-lang/chapel/blob/master/test/classes/initializers/generics/param-field-default-value-non-param-field.chpl
          ) #8453 

[ edit 2/17 cassella to add pointer to future. ]

### Configuration Information

```
fortytwo@magrathea:~/src/chapel/test (param-field-default-value-non-param-field)$ chpl --version
chpl version 1.17.0 pre-release (2d81356)
Copyright (c) 2004-2018, Cray Inc.  (See LICENSE file for more details)

fortytwo@magrathea:~/src/chapel/test (param-field-default-value-non-param-field)$ printchplenv --anonymize
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: gasnet *
  CHPL_COMM_SUBSTRATE: udp
  CHPL_GASNET_SEGMENT: everything
CHPL_TASKS: qthreads
CHPL_LAUNCHER: amudprun
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: intrinsics
  CHPL_NETWORK_ATOMICS: none
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_AUX_FILESYS: none

fortytwo@magrathea:~/src/chapel/test (param-field-default-value-non-param-field)$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609
```

**Comment by lydia-duncan** [comment]
Thanks for finding this, it is definitely worth a test of its own

**Comment by cassella** [comment]
Run with --gdb:

```
chpl --gdb test/classes/initializers/generics/param-field-default-value-non-param-field.chpl
...
(gdb) r
Starting program: /home/fortytwo/src/chapel/bin/linux64/chpl test/classes/initializers/generics/param-field-default-value-non-param-field.chpl

Program received signal SIGSEGV, Segmentation fault.
0x000000000048a835 in Expr::isRef (this=0x0) at expr.cpp:125
125       return this->qualType().isRef();
(gdb) bt          
#0  0x000000000048a835 in Expr::isRef (this=0x0) at expr.cpp:125
#1  0x000000000048a92a in Expr::isRefOrWideRef (this=0x0) at expr.cpp:139
#2  0x00000000005fe268 in fixAST () at insertWideReferences.cpp:2170
#3  0x0000000000600b51 in insertWideReferences () at insertWideReferences.cpp:2596
#4  0x0000000000565764 in runPass (tracker=..., passIndex=35, isChpldoc=false) at runpasses.cpp:202
#5  0x0000000000565678 in runPasses (tracker=..., isChpldoc=false) at runpasses.cpp:169
#6  0x0000000000560889 in main (argc=2, argv=0x7fffffffe1f8) at driver.cpp:1345
```

and with --verify:

```
fortytwo@magrathea:~/src/chapel (param-field-default-value-non-param)$ chpl --verify test/classes/initializers/generics/param-field-default-value-non-param-field.chpl 
$CHPL_HOME/modules/internal/ChapelIO.chpl:255: In function 'writeThisFieldsDefaultImpl':
$CHPL_HOME/modules/internal/ChapelIO.chpl:279: internal error: Refers to a local/arg in another function [checkAST.cpp:69]
```
