### ISSUE TITLE
Trouble installing Mason

### ISSUE THREAD

**Issue by buddha314** [chapel-lang/chapel#8766]
Okay, from the top.

I had `mason` in `/usr/local/bin`. I removed that.  I went into my chapel dir, did `make clobber; make all`.  Then went into `tools/mason` and did `make; make install`.

However, it looks like it put the "mason" binary in the subdirectory and did not link it back to `/usr/local/bin`.

```
make install
Installing symbolic link...
cd /Users/buddha/github/chapel/bin/darwin && ln -s ../../tools/mason/mason mason
```

How do I get it back into `/usr/local/bin`?

**Comment by ben-albrecht** [comment]
Try: `make install` from `$CHPL_HOME`

**Comment by buddha314** [comment]
Stuckified!  From the chapel home directory

```
:chapel buddha$ pwd
/Users/buddha/github/chapel
macbuddha:chapel buddha$ make mason
cd compiler && /Applications/Xcode.app/Contents/Developer/usr/bin/make
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C /Users/buddha/github/chapel/third-party/llvm none
make[2]: Nothing to be done for `none'.
***** adt/ *****
***** AST/ *****
***** backend/ *****
***** codegen/ *****
***** ifa/ *****
***** ipe/ *****
***** main/ *****
***** optimizations/ *****
***** parser/ *****
***** passes/ *****
***** resolution/ *****
***** util/ *****
***** ./ *****
cd chpl-venv && /Applications/Xcode.app/Contents/Developer/usr/bin/make chpldoc-venv
export PYTHONPATH=/Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6:$PYTHONPATH && \
	/usr/local/bin/easy_install --install-dir=/Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6 virtualenv==12.0.5
Searching for virtualenv==12.0.5
Best match: virtualenv 12.0.5
Processing virtualenv-12.0.5-py3.6.egg
virtualenv 12.0.5 is already the active version in easy-install.pth
Installing virtualenv script to /Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6
Installing virtualenv-3.4 script to /Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6

Using /Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/virtualenv-12.0.5-py3.6.egg
Processing dependencies for virtualenv==12.0.5
Finished processing dependencies for virtualenv==12.0.5
install/darwin/py3.6/virtualenv --python=/usr/local/bin/python /Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/chpl-virtualenv
Running virtualenv with interpreter /usr/local/bin/python
Using base prefix '/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/chpl-virtualenv/bin/python3.6
Not overwriting existing python script /Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/chpl-virtualenv/bin/python (you must use /Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/chpl-virtualenv/bin/python3.6)
Installing setuptools, pip...
  Complete output from command /Users/buddha/github...ualenv/bin/python3.6 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/virtualenv-12.0.5-py3.6.egg/virtualenv_support/pip-6.0.6-py2.py3-none-any.whl/pip/__init__.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/virtualenv-12.0.5-py3.6.egg/virtualenv_support/pip-6.0.6-py2.py3-none-any.whl/pip/utils/__init__.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/virtualenv-12.0.5-py3.6.egg/virtualenv_support/pip-6.0.6-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 1649, in <module>
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
----------------------------------------
...Installing setuptools, pip...done.
Traceback (most recent call last):
  File "/Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/virtualenv-12.0.5-py3.6.egg/virtualenv.py", line 2352, in <module>
    main()
  File "/Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/virtualenv-12.0.5-py3.6.egg/virtualenv.py", line 825, in main
    symlink=options.symlink)
  File "/Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/virtualenv-12.0.5-py3.6.egg/virtualenv.py", line 993, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/virtualenv-12.0.5-py3.6.egg/virtualenv.py", line 961, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/virtualenv-12.0.5-py3.6.egg/virtualenv.py", line 903, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/buddha/github...ualenv/bin/python3.6 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1
make[2]: *** [/Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/chpl-virtualenv] Error 1
make[1]: *** [/Users/buddha/github/chapel/third-party/chpl-venv/install/darwin/py3.6/chpl-virtualenv/bin/sphinx-build] Error 2
make: [third-party-chpldoc-venv] Error 2 (ignored)
cd compiler && /Applications/Xcode.app/Contents/Developer/usr/bin/make chpldoc
make[1]: Nothing to be done for `chpldoc'.
cd man && /Applications/Xcode.app/Contents/Developer/usr/bin/make chpldoc
make[2]: Nothing to be done for `chpldoc'.
cd tools/mason && /Applications/Xcode.app/Contents/Developer/usr/bin/make && /Applications/Xcode.app/Contents/Developer/usr/bin/make install
make[1]: Nothing to be done for `default'.
Removing old symbolic link...
rm -f /Users/buddha/github/chapel/bin/darwin/mason

Installing symbolic link...
cd /Users/buddha/github/chapel/bin/darwin && ln -s ../../tools/mason/mason mason
```

And then...
```
make install
cd compiler && /Applications/Xcode.app/Contents/Developer/usr/bin/make
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C /Users/buddha/github/chapel/third-party/llvm none
make[3]: Nothing to be done for `none'.
***** adt/ *****
***** AST/ *****
***** backend/ *****
***** codegen/ *****
***** ifa/ *****
***** ipe/ *****
***** main/ *****
***** optimizations/ *****
***** parser/ *****
***** passes/ *****
***** resolution/ *****
***** util/ *****
***** ./ *****
Speculatively attempting to build re2
make[3]: Nothing to be done for `re2'.
Speculatively attempting to build gmp
make[3]: Nothing to be done for `gmp'.
cd runtime && /Applications/Xcode.app/Contents/Developer/usr/bin/make
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C /Users/buddha/github/chapel/third-party hwloc
make[3]: Nothing to be done for `hwloc'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C /Users/buddha/github/chapel/third-party jemalloc
make[3]: Nothing to be done for `jemalloc'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C /Users/buddha/github/chapel/third-party hwloc gmp re2 jemalloc qthread
make[3]: Nothing to be done for `hwloc'.
make[3]: Nothing to be done for `gmp'.
make[3]: Nothing to be done for `re2'.
make[3]: Nothing to be done for `jemalloc'.
make[3]: Nothing to be done for `qthread'.
***** src/comm/ *****
***** src/comm/none/ *****
***** src/mem/ *****
***** src/mem/jemalloc/ *****
***** src/tasks/ *****
***** src/tasks/qthreads/ *****
***** src/threads/ *****
***** src/threads/none/ *****
***** src/timers/ *****
***** src/timers/generic/ *****
***** src/qio/regexp/re2/ *****
***** src/qio/auxFilesys/hdfs/ *****
***** src/qio/auxFilesys/curl/ *****
***** src/qio/ *****
***** src/ *****
***** ./ *****
cd modules && /Applications/Xcode.app/Contents/Developer/usr/bin/make
make[2]: Nothing to be done for `default'.
Exiting: Installation path not configured.
         See ./configure --help
make: *** [install] Error 255
macbuddha:chapel buddha$ mason
-bash: /usr/local/bin/mason: No such file or directory
```

**Comment by ben-albrecht** [comment]
`make mason` failed because building `chpldoc` failed, which appears to be due to building with Python 3 (#8756).

`make install` failed because:

```
Exiting: Installation path not configured.
         See ./configure --help
```

**Comment by buddha314** [comment]
k, ran `./configure` and will see what happens

**Comment by buddha314** [comment]
Seems as if he magic incantation is

```
./configure
./make
./make install
```

then mason is back.

**Comment by ben-albrecht** [comment]
Great! Shall we close this issue?

**Comment by ben-albrecht** [comment]
@buddha314 - I'm closing this one, since other issues document the desire for python 3 support with `chpldoc`. Let me know if it should be reopened for a separate reason.
